//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Map2Civilization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Map2Civilization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap About_Image {
            get {
                object obj = ResourceManager.GetObject("About_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Block1_v5 {
            get {
                object obj = ResourceManager.GetObject("Block1_v5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Block2_v5 {
            get {
                object obj = ResourceManager.GetObject("Block2_v5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BugLarge_Image {
            get {
                object obj = ResourceManager.GetObject("BugLarge_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cancel_Image {
            get {
                object obj = ResourceManager.GetObject("Cancel_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanvasResize_Image {
            get {
                object obj = ResourceManager.GetObject("CanvasResize_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Earth_Image {
            get {
                object obj = ResourceManager.GetObject("Earth_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Export_Image {
            get {
                object obj = ResourceManager.GetObject("Export_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help_Image {
            get {
                object obj = ResourceManager.GetObject("Help_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Info_Image {
            get {
                object obj = ResourceManager.GetObject("Info_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LockedTile_Image {
            get {
                object obj = ResourceManager.GetObject("LockedTile_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MagLens_Image {
            get {
                object obj = ResourceManager.GetObject("MagLens_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MeasuringTape_Image {
            get {
                object obj = ResourceManager.GetObject("MeasuringTape_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimap_Image {
            get {
                object obj = ResourceManager.GetObject("Minimap_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MiniRuler_Image {
            get {
                object obj = ResourceManager.GetObject("MiniRuler_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MiniWorldGrid_Image {
            get {
                object obj = ResourceManager.GetObject("MiniWorldGrid_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap New_Image {
            get {
                object obj = ResourceManager.GetObject("New_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OK_Image {
            get {
                object obj = ResourceManager.GetObject("OK_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open_Image {
            get {
                object obj = ResourceManager.GetObject("Open_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Palette_Image {
            get {
                object obj = ResourceManager.GetObject("Palette_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PenRulerLarge_Image {
            get {
                object obj = ResourceManager.GetObject("PenRulerLarge_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save_Image {
            get {
                object obj = ResourceManager.GetObject("Save_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SaveAs_Image {
            get {
                object obj = ResourceManager.GetObject("SaveAs_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Select_Image {
            get {
                object obj = ResourceManager.GetObject("Select_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SelectOff_Image {
            get {
                object obj = ResourceManager.GetObject("SelectOff_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings_Image {
            get {
                object obj = ResourceManager.GetObject("Settings_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map2Civilization is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.
        ///
        ///Map2Civilization is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
        ///
        ///You should have received [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Str_AboutBox_CopyrightInfo {
            get {
                return ResourceManager.GetString("Str_AboutBox_CopyrightInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Str_AboutForm_About {
            get {
                return ResourceManager.GetString("Str_AboutForm_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Str_AboutForm_Version {
            get {
                return ResourceManager.GetString("Str_AboutForm_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating new model..
        /// </summary>
        internal static string Str_AnalyserReliefMap_ErrorCreatingModel {
            get {
                return ResourceManager.GetString("Str_AnalyserReliefMap_ErrorCreatingModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New model created...
        /// </summary>
        internal static string Str_AnalyserReliefMap_ModelCreated {
            get {
                return ResourceManager.GetString("Str_AnalyserReliefMap_ModelCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhombus is not currently supported.
        /// </summary>
        internal static string Str_BitmapOperations_RhombusNotSupported {
            get {
                return ResourceManager.GetString("Str_BitmapOperations_RhombusNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duel (40x25).
        /// </summary>
        internal static string Str_CivilizationVersion_Civilization5MapSizes_Duel {
            get {
                return ResourceManager.GetString("Str_CivilizationVersion_Civilization5MapSizes_Duel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huge (128x80).
        /// </summary>
        internal static string Str_CivilizationVersion_Civilization5MapSizes_Huge {
            get {
                return ResourceManager.GetString("Str_CivilizationVersion_Civilization5MapSizes_Huge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humongous ** For Debugging Purposes Only ** (300,200).
        /// </summary>
        internal static string Str_CivilizationVersion_Civilization5MapSizes_Humongous {
            get {
                return ResourceManager.GetString("Str_CivilizationVersion_Civilization5MapSizes_Humongous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large (104x64).
        /// </summary>
        internal static string Str_CivilizationVersion_Civilization5MapSizes_Large {
            get {
                return ResourceManager.GetString("Str_CivilizationVersion_Civilization5MapSizes_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small (66x42).
        /// </summary>
        internal static string Str_CivilizationVersion_Civilization5MapSizes_Small {
            get {
                return ResourceManager.GetString("Str_CivilizationVersion_Civilization5MapSizes_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard (80x52.
        /// </summary>
        internal static string Str_CivilizationVersion_Civilization5MapSizes_Standard {
            get {
                return ResourceManager.GetString("Str_CivilizationVersion_Civilization5MapSizes_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiny (56x36).
        /// </summary>
        internal static string Str_CivilizationVersion_Civilization5MapSizes_Tiny {
            get {
                return ResourceManager.GetString("Str_CivilizationVersion_Civilization5MapSizes_Tiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string Str_ColorSelector_RGBSeparator {
            get {
                return ResourceManager.GetString("Str_ColorSelector_RGBSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !.
        /// </summary>
        internal static string Str_ExporterBase_NotSupportedCaption {
            get {
                return ResourceManager.GetString("Str_ExporterBase_NotSupportedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option .
        /// </summary>
        internal static string Str_ExporterBase_NotSupportedMessagePart1 {
            get {
                return ResourceManager.GetString("Str_ExporterBase_NotSupportedMessagePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not currently implemented...
        /// </summary>
        internal static string Str_ExporterBase_NotSupportedMessagePart2 {
            get {
                return ResourceManager.GetString("Str_ExporterBase_NotSupportedMessagePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported model to map .
        /// </summary>
        internal static string Str_ExporterCivilizationV_ExportedMessage {
            get {
                return ResourceManager.GetString("Str_ExporterCivilizationV_ExportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexagonal (Pointy Topped).
        /// </summary>
        internal static string Str_GridType_GridTypeDescriptions_HexagonalPT {
            get {
                return ResourceManager.GetString("Str_GridType_GridTypeDescriptions_HexagonalPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhombus.
        /// </summary>
        internal static string Str_GridType_GridTypeDescriptions_Rhombus {
            get {
                return ResourceManager.GetString("Str_GridType_GridTypeDescriptions_Rhombus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        internal static string Str_GridType_GridTypeDescriptions_Square {
            get {
                return ResourceManager.GetString("Str_GridType_GridTypeDescriptions_Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image height: .
        /// </summary>
        internal static string Str_ImageEditor_ImageHeight {
            get {
                return ResourceManager.GetString("Str_ImageEditor_ImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixels.
        /// </summary>
        internal static string Str_ImageEditor_ImagePixels {
            get {
                return ResourceManager.GetString("Str_ImageEditor_ImagePixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image width: .
        /// </summary>
        internal static string Str_ImageEditor_ImageWidth {
            get {
                return ResourceManager.GetString("Str_ImageEditor_ImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intended Ratio:.
        /// </summary>
        internal static string Str_ImageEditor_IntendedRatio {
            get {
                return ResourceManager.GetString("Str_ImageEditor_IntendedRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid selection..
        /// </summary>
        internal static string Str_KeyboardShortcutSelector_MessageBoxAlreadyAssignedCaption {
            get {
                return ResourceManager.GetString("Str_KeyboardShortcutSelector_MessageBoxAlreadyAssignedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key combination is already assigned to another shortcut..
        /// </summary>
        internal static string Str_KeyboardShortcutSelector_MessageBoxAlreadyAssignedText {
            get {
                return ResourceManager.GetString("Str_KeyboardShortcutSelector_MessageBoxAlreadyAssignedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input..
        /// </summary>
        internal static string Str_KeyboardShortcutSelectorForm_ModifierRequiredCaption {
            get {
                return ResourceManager.GetString("Str_KeyboardShortcutSelectorForm_ModifierRequiredCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This shortcut requires that at least on key modifier (Control and/or Alt) are applied to it..
        /// </summary>
        internal static string Str_KeyboardShortcutSelectorForm_ModifierRequiredText {
            get {
                return ResourceManager.GetString("Str_KeyboardShortcutSelectorForm_ModifierRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while performing asynchronous operation..
        /// </summary>
        internal static string Str_LoadModelProcessor_AsyncError {
            get {
                return ResourceManager.GetString("Str_LoadModelProcessor_AsyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while performing asynchronous operation..
        /// </summary>
        internal static string Str_LoadModelProcessor_FileError {
            get {
                return ResourceManager.GetString("Str_LoadModelProcessor_FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded file .
        /// </summary>
        internal static string Str_LoadModelProcessor_FileLoaded {
            get {
                return ResourceManager.GetString("Str_LoadModelProcessor_FileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Str_MainForm_CoordinateSeparator {
            get {
                return ResourceManager.GetString("Str_MainForm_CoordinateSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo-Data provider.
        /// </summary>
        internal static string Str_MapDataSource_Description_GeoData {
            get {
                return ResourceManager.GetString("Str_MapDataSource_Description_GeoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relief Map Image File.
        /// </summary>
        internal static string Str_MapDataSource_Description_ReliefMapImage {
            get {
                return ResourceManager.GetString("Str_MapDataSource_Description_ReliefMapImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing Plots (.
        /// </summary>
        internal static string Str_NewMapForm_AnalysingPlotsPart1 {
            get {
                return ResourceManager.GetString("Str_NewMapForm_AnalysingPlotsPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Done).
        /// </summary>
        internal static string Str_NewMapForm_AnalysingPlotsPart2 {
            get {
                return ResourceManager.GetString("Str_NewMapForm_AnalysingPlotsPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Analysis Image.
        /// </summary>
        internal static string Str_NewMapForm_CreatingAnalysisImage {
            get {
                return ResourceManager.GetString("Str_NewMapForm_CreatingAnalysisImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Error.
        /// </summary>
        internal static string Str_NewMapForm_UnhandledError {
            get {
                return ResourceManager.GetString("Str_NewMapForm_UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.M2C.
        /// </summary>
        internal static string Str_OpenFileDialogDefaultExt {
            get {
                return ResourceManager.GetString("Str_OpenFileDialogDefaultExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map2Civ Files | *.M2C.
        /// </summary>
        internal static string Str_OpenFileDialogFilter {
            get {
                return ResourceManager.GetString("Str_OpenFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo-Data feature is not implemented yet..
        /// </summary>
        internal static string Str_PlotGeoData_NotSupported {
            get {
                return ResourceManager.GetString("Str_PlotGeoData_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Editor.
        /// </summary>
        internal static string Str_ProcessedMapControlMode_Description_ColorEditor {
            get {
                return ResourceManager.GetString("Str_ProcessedMapControlMode_Description_ColorEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot Editor.
        /// </summary>
        internal static string Str_ProcessedMapControlMode_Description_PlotEditors {
            get {
                return ResourceManager.GetString("Str_ProcessedMapControlMode_Description_PlotEditors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Terrain Assignment.
        /// </summary>
        internal static string Str_ProcessedMapMenu_DeAssign_Text {
            get {
                return ResourceManager.GetString("Str_ProcessedMapMenu_DeAssign_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Plot Color (.
        /// </summary>
        internal static string Str_ProcessedMapMenu_EditPlotColor_Text {
            get {
                return ResourceManager.GetString("Str_ProcessedMapMenu_EditPlotColor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Region (.
        /// </summary>
        internal static string Str_ProcessedMapMenu_EditRegion_Text {
            get {
                return ResourceManager.GetString("Str_ProcessedMapMenu_EditRegion_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Center on selected plot.
        /// </summary>
        internal static string Str_RegionEditForm_AutoCenterBox {
            get {
                return ResourceManager.GetString("Str_RegionEditForm_AutoCenterBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving model..
        /// </summary>
        internal static string Str_SaveModelProcessor_SavedError {
            get {
                return ResourceManager.GetString("Str_SaveModelProcessor_SavedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved file .
        /// </summary>
        internal static string Str_SaveModelProcessor_SavedFile {
            get {
                return ResourceManager.GetString("Str_SaveModelProcessor_SavedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non acceptable value.
        /// </summary>
        internal static string Str_SettingsForm_MaximumZoomErrorCaption {
            get {
                return ResourceManager.GetString("Str_SettingsForm_MaximumZoomErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum zoom value must be greater than 100.
        /// </summary>
        internal static string Str_SettingsForm_MaximumZoomErrorText {
            get {
                return ResourceManager.GetString("Str_SettingsForm_MaximumZoomErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non acceptable value.
        /// </summary>
        internal static string Str_SettingsForm_MinimumZoomErrorCaption {
            get {
                return ResourceManager.GetString("Str_SettingsForm_MinimumZoomErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum zoom value must be smaller than 100.
        /// </summary>
        internal static string Str_SettingsForm_MinimumZoomErrorText {
            get {
                return ResourceManager.GetString("Str_SettingsForm_MinimumZoomErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non acceptable value.
        /// </summary>
        internal static string Str_SettingsForm_PlotWidthErrorCaption {
            get {
                return ResourceManager.GetString("Str_SettingsForm_PlotWidthErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Required.
        /// </summary>
        internal static string Str_SettingsForm_RestartCaption {
            get {
                return ResourceManager.GetString("Str_SettingsForm_RestartCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes you have made, require an application restart..
        /// </summary>
        internal static string Str_SettingsForm_RestartText {
            get {
                return ResourceManager.GetString("Str_SettingsForm_RestartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non acceptable value.
        /// </summary>
        internal static string Str_SettingsForm_ZoomErrorCaption {
            get {
                return ResourceManager.GetString("Str_SettingsForm_ZoomErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum zoom value should be smaller than the maximum zoom value..
        /// </summary>
        internal static string Str_SettingsForm_ZoomErrorText {
            get {
                return ResourceManager.GetString("Str_SettingsForm_ZoomErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        internal static string Str_SingleColonWithSpace {
            get {
                return ResourceManager.GetString("Str_SingleColonWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string Str_SingleSpace {
            get {
                return ResourceManager.GetString("Str_SingleSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while opening image map file..
        /// </summary>
        internal static string Str_SourceSettingsControlReliefMap_ErrorOpeningFile {
            get {
                return ResourceManager.GetString("Str_SourceSettingsControlReliefMap_ErrorOpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Image Ratio..
        /// </summary>
        internal static string Str_SourceSettingsControlReliefMap_ImageSizeMsgBoxWaringCaption {
            get {
                return ResourceManager.GetString("Str_SourceSettingsControlReliefMap_ImageSizeMsgBoxWaringCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected image&apos;s size is not compatible with the dimensions of the map. Would you like to select the portion of the image to be transferred to the map?.
        /// </summary>
        internal static string Str_SourceSettingsControlReliefMap_ImageSizeMsgBoxWaringText {
            get {
                return ResourceManager.GetString("Str_SourceSettingsControlReliefMap_ImageSizeMsgBoxWaringText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image file selected. Please select a valid image file and try again.
        /// </summary>
        internal static string Str_SourceSettingsControlReliefMap_NoImageSelected {
            get {
                return ResourceManager.GetString("Str_SourceSettingsControlReliefMap_NoImageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coast.
        /// </summary>
        internal static string Str_TerrainType_Description_Coast {
            get {
                return ResourceManager.GetString("Str_TerrainType_Description_Coast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain.
        /// </summary>
        internal static string Str_TerrainType_Description_Flat {
            get {
                return ResourceManager.GetString("Str_TerrainType_Description_Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hill.
        /// </summary>
        internal static string Str_TerrainType_Description_Hill {
            get {
                return ResourceManager.GetString("Str_TerrainType_Description_Hill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountain.
        /// </summary>
        internal static string Str_TerrainType_Description_Mountain {
            get {
                return ResourceManager.GetString("Str_TerrainType_Description_Mountain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Defined.
        /// </summary>
        internal static string Str_TerrainType_Description_NotDefined {
            get {
                return ResourceManager.GetString("Str_TerrainType_Description_NotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocean.
        /// </summary>
        internal static string Str_TerrainType_Description_Ocean {
            get {
                return ResourceManager.GetString("Str_TerrainType_Description_Ocean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! There seems to be a problem that wasn&apos;t handled at all....
        /// </summary>
        internal static string Str_UnhandledError {
            get {
                return ResourceManager.GetString("Str_UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom:.
        /// </summary>
        internal static string Str_ZoomSplitButtonText {
            get {
                return ResourceManager.GetString("Str_ZoomSplitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string Str_ZoomSplitButtonText_Percent {
            get {
                return ResourceManager.GetString("Str_ZoomSplitButtonText_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Terrain_Image {
            get {
                object obj = ResourceManager.GetObject("Terrain_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intended Ratio:.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WarningLarge_Image {
            get {
                object obj = ResourceManager.GetObject("WarningLarge_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon WorldMap16_32 {
            get {
                object obj = ResourceManager.GetObject("WorldMap16_32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon WorldMap64_256 {
            get {
                object obj = ResourceManager.GetObject("WorldMap64_256", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WorldMapLarge_Image {
            get {
                object obj = ResourceManager.GetObject("WorldMapLarge_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Zoom_in_Image {
            get {
                object obj = ResourceManager.GetObject("Zoom_in_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Zoom_out_Image {
            get {
                object obj = ResourceManager.GetObject("Zoom_out_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Zoom100_Image {
            get {
                object obj = ResourceManager.GetObject("Zoom100_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
