//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Map2Civilization.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 192")]
        public global::System.Drawing.Color PlotColorOcean {
            get {
                return ((global::System.Drawing.Color)(this["PlotColorOcean"]));
            }
            set {
                this["PlotColorOcean"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 255, 255")]
        public global::System.Drawing.Color PlotColorCoast {
            get {
                return ((global::System.Drawing.Color)(this["PlotColorCoast"]));
            }
            set {
                this["PlotColorCoast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color PlotColorFlat {
            get {
                return ((global::System.Drawing.Color)(this["PlotColorFlat"]));
            }
            set {
                this["PlotColorFlat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color PlotColorHill {
            get {
                return ((global::System.Drawing.Color)(this["PlotColorHill"]));
            }
            set {
                this["PlotColorHill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color PlotColorMountain {
            get {
                return ((global::System.Drawing.Color)(this["PlotColorMountain"]));
            }
            set {
                this["PlotColorMountain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Map2CivReport@gmail.com")]
        public string ReportEMailAddress {
            get {
                return ((string)(this["ReportEMailAddress"]));
            }
            set {
                this["ReportEMailAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int PlotWidthPixelsSquarePlot {
            get {
                return ((int)(this["PlotWidthPixelsSquarePlot"]));
            }
            set {
                this["PlotWidthPixelsSquarePlot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int PlotWidthPixelsHexagonalP {
            get {
                return ((int)(this["PlotWidthPixelsHexagonalP"]));
            }
            set {
                this["PlotWidthPixelsHexagonalP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int PlotWidthPixelsRhombus {
            get {
                return ((int)(this["PlotWidthPixelsRhombus"]));
            }
            set {
                this["PlotWidthPixelsRhombus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color MapGridColorModel {
            get {
                return ((global::System.Drawing.Color)(this["MapGridColorModel"]));
            }
            set {
                this["MapGridColorModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ProcessedMapUnAssignedPlotGridColor {
            get {
                return ((global::System.Drawing.Color)(this["ProcessedMapUnAssignedPlotGridColor"]));
            }
            set {
                this["ProcessedMapUnAssignedPlotGridColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public float MinZoomPercent {
            get {
                return ((float)(this["MinZoomPercent"]));
            }
            set {
                this["MinZoomPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public float MaxZoomPercent {
            get {
                return ((float)(this["MaxZoomPercent"]));
            }
            set {
                this["MaxZoomPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float ZoomStepPercent {
            get {
                return ((float)(this["ZoomStepPercent"]));
            }
            set {
                this["ZoomStepPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fuchsia")]
        public global::System.Drawing.Color ProcessedMapHighlightedPlotGridColor {
            get {
                return ((global::System.Drawing.Color)(this["ProcessedMapHighlightedPlotGridColor"]));
            }
            set {
                this["ProcessedMapHighlightedPlotGridColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ProcessedMapHighlightedPlotGridWidthPixels {
            get {
                return ((int)(this["ProcessedMapHighlightedPlotGridWidthPixels"]));
            }
            set {
                this["ProcessedMapHighlightedPlotGridWidthPixels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+N")]
        public global::System.Windows.Forms.Keys KeyShrortcuts_NewModel {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyShrortcuts_NewModel"]));
            }
            set {
                this["KeyShrortcuts_NewModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+S")]
        public global::System.Windows.Forms.Keys KeyShrortcuts_Save {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyShrortcuts_Save"]));
            }
            set {
                this["KeyShrortcuts_Save"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Shift+S")]
        public global::System.Windows.Forms.Keys KeyShrortcuts_SaveAs {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyShrortcuts_SaveAs"]));
            }
            set {
                this["KeyShrortcuts_SaveAs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+E")]
        public global::System.Windows.Forms.Keys KeyShrortcuts_ExportToCivMap {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyShrortcuts_ExportToCivMap"]));
            }
            set {
                this["KeyShrortcuts_ExportToCivMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+C")]
        public global::System.Windows.Forms.Keys KeyShrortcuts_EditPlotData {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyShrortcuts_EditPlotData"]));
            }
            set {
                this["KeyShrortcuts_EditPlotData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+R")]
        public global::System.Windows.Forms.Keys KeyShrortcuts_EditRegion {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyShrortcuts_EditRegion"]));
            }
            set {
                this["KeyShrortcuts_EditRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+O")]
        public global::System.Windows.Forms.Keys KeyShrortcuts_AssignOcean {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyShrortcuts_AssignOcean"]));
            }
            set {
                this["KeyShrortcuts_AssignOcean"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public global::System.Windows.Forms.Keys KeyShrortcuts_AssignCoast {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyShrortcuts_AssignCoast"]));
            }
            set {
                this["KeyShrortcuts_AssignCoast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F")]
        public global::System.Windows.Forms.Keys KeyShrortcuts_AssignFlat {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyShrortcuts_AssignFlat"]));
            }
            set {
                this["KeyShrortcuts_AssignFlat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H")]
        public global::System.Windows.Forms.Keys KeyShrortcuts_AssignHill {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyShrortcuts_AssignHill"]));
            }
            set {
                this["KeyShrortcuts_AssignHill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M")]
        public global::System.Windows.Forms.Keys KeyShrortcuts_AssignMountain {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyShrortcuts_AssignMountain"]));
            }
            set {
                this["KeyShrortcuts_AssignMountain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys Setting {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Default)")]
        public global::System.Globalization.CultureInfo UICulture {
            get {
                return ((global::System.Globalization.CultureInfo)(this["UICulture"]));
            }
            set {
                this["UICulture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+O")]
        public global::System.Windows.Forms.Keys KeyShrortcuts_OpenModel {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyShrortcuts_OpenModel"]));
            }
            set {
                this["KeyShrortcuts_OpenModel"] = value;
            }
        }
    }
}
